 steps:
 - name: 'gcr.io/cloud-builders/git'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     git clone https://github.com/Guddumbhagyasri/APIGEE-GCP.git
     cd APIGEE-GCP
     chmod +x script.sh
    
