 steps:
 - name: 'gcr.io/cloud-builders/git'
   args: ['clone', 'https://github.com/Guddumbhagyasri/APIGEE-GCP.git']
   dir : 'APIGEE-GCP'
 - name: 'bash'
   args: ['-c', 'yum install git -y', 'chmod +x script.sh']
   args: ['sh', 'script.sh']

