#steps:
#- name: 'gcr.io/cloud-builders/mvn'
 # args: ['install', '-P', 'Prod']
  #dir: 'HelloWorld'
# TODO setup Apigee account secret using encrypted variables
steps:
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: [
      'beta', 
      'functions',
      'mvn apigee-enterprise:deploy -Pprod -Dusername=g.bhagya9@gmail.com -Dpassword=BhagiReddy30@$',
      # mvn apigee-enterprise:deploy -Pprod -Dusername=g.bhagya9@gmail.com -Dpassword=BhagiReddy30@$
      '--
#source=https://source.developers.google.com/projects/${vernal-period-269422}/repos/default/moveable-aliases/master/paths/',
#      '--trigger-bucket=${_ROOT}-trigger',
#      '--entry-point= 'bash',
#      '--project=${vernal-period-269422}'
  dir: 'HelloWorld'
  #secretEnv: ['PASSWORD']
  
#secrets:
#- kmsKeyName: projects/lustrous-bonito-250717/locations/global/keyRings/Apigee-cicd/cryptoKeys/APIGEE
#  secretEnv:
#    PASSWORD: CiQA7O+Oy13E4yvbkxztFSng23yIhU3kczwtYMU8qYn40r622kgSKwAX3d/GMN3T0MU7YwHkYQb9BzOTRrf72zQ1Sbflmc2BcHYllTTuPOaZqro=
