 steps:
 - name: 'gcr.io/cloud-builders/git'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     git fetch

     #git branch --sort=committerdate | xargs echo
   
     for branch in $(git branch -r --merged | grep -v HEAD | grep -v QA | grep -v QA | grep -v QA | sed /\*/d); do [ "$(git log -1 --since='Jun 20, 2021' -s ${branch})" ]; echo -e `git show --format="%ci %cr %an" ${branch} | head -n 1` \\t$branch]; done
     # if [ -z "$(git log -1 --since='Jun 10, 2020' -s ${branch})" ]; then
     #      echo -e `git show --format="%ci %cr %an" ${branch} | head -n 1` \\t$branch
     #      remote_branch=$(echo ${branch} | sed 's#origin/##' )
     #          #git push origin --delete ${remote_branch}
     #   fi
    


